version: '3.8'
services:
  server:
    build:
      context: .
    entrypoint: entrypoint.sh # Script in charge on running migrations.
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/stant_challenge:cached
    deploy:
      replicas: 5
      placement:
        constraints: [node.role == worker]

    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      WAIT_HOSTS: database_postgresql:5432
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    depends_on:
      - database_postgresql
    stdin_open: true
    tty: true

  database_postgresql:
    image: postgres:14.0
    restart: always
    environment:
      POSTGRESQL_DATABASE: swarm_test
      POSTGRESQL_HOST: postgres
      POSTGRESQL_ROOT_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    deploy:
      replicas: 5
      placement:
        constraints: [node.role == manager]

  visualizer:
    image: dockersamples/visualizer:stable
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
    - "8080:8080"
    deploy:
      replicas: 5
      placement:
        constraints: [node.role == manager]